USE nirzj0shn94smawo;

DROP TABLE IF EXISTS name_has_genres;
DROP TABLE IF EXISTS name_has_themes;
DROP TABLE IF EXISTS directors;
DROP TABLE IF EXISTS studios;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS themes;
DROP TABLE IF EXISTS anime;